### ISSUE TITLE
issues when building docker image

### ISSUE THREAD

**Issue by gchaperon** [KTH/chai#21]
hi!

when building the docker image with `docker build .`, the building process completes sucessfully but one command in the `setup_env.sh` script fails "silently" (execution continues, but errors ar printed).

here is the relvant part from the build logs, produced by [this command](https://github.com/KTH/chai/blob/master/src/setup_env.sh#L57):
```
Cloning OpenNMT-py
Cloning into '/SequenceR/src/lib/OpenNMT-py'...
Installing requirements for OpenNMT-py
Collecting git+https://github.com/pytorch/text (from -r /SequenceR/src/lib/OpenNMT-py/requirements.txt (line 4))
  Cloning https://github.com/pytorch/text to /tmp/pip-4ob0llr2-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-4ob0llr2-build/setup.py", line 10, in <module>
        from build_tools import setup_helpers
      File "/tmp/pip-4ob0llr2-build/build_tools/setup_helpers/__init__.py", line 1, in <module>
        from .extension import *  # noqa
      File "/tmp/pip-4ob0llr2-build/build_tools/setup_helpers/extension.py", line 6, in <module>
        from torch.utils.cpp_extension import (
    ModuleNotFoundError: No module named 'torch'
    
    ----------------------------------------
```

While the build technically finishes successfully, doing something like `cd src && ./sequencer-text.sh` inside the image fails immediately with:
```
sequencer-train.sh start
Starting data preprocessing
Traceback (most recent call last):
  File "preprocess.py", line 7, in <module>
    import configargparse
ModuleNotFoundError: No module named 'configargparse'
Starting training
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    import configargparse
ModuleNotFoundError: No module named 'configargparse'
sequencer-train.sh done

root@5102c16e3c19:/SequenceR/src# ./sequencer-test.sh
sequencer-test.sh start
Starting test data translation
Traceback (most recent call last):
  File "translate.py", line 5, in <module>
    import configargparse
ImportError: No module named configargparse
sequencer-test.sh done
```

I think we could use `set -e` at the beginning of `setup_env.sh` to uncover these kinds of issue, so that the build actually fails if anything goes wrong.

I wanted to post my full logs, but they are too long for github and pastebin.com, if its necessary please let me know and I'll figure.

**Comment by chenzimin** [comment]
Hi Gabriel, can you check if it is working for you now?

**Comment by gchaperon** [comment]
hi zimin, i am still having some trouble

i am getting the following
```
Collecting pandas>=0.23 (from seaborn->-r /SequenceR/src/lib/OpenNMT-py/requirements.txt (line 9))
  Downloading https://files.pythonhosted.org/packages/78/e4/a935f1701fac697c6c5458f86968bec5d2b4cb66e7f738225216ebaa20b4/pandas-1.2.2.tar.gz (5.5MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-56t1_unw/pandas/setup.py", line 20, in <module>
        import numpy
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
```

i think this error is produced because `seaborn` from `requirements.txt` in OpenNMT doesn't have its dependencies pinned, ie `pandas>=0.23` which currently is `1.2.2`. This version uses a different build system/build spec, specified by pep517 & 518, where the requierement for the _build process_ are specified differently, meaning that numpy is actually a requirement for building pandas and not just for running / using the library. I think that is why pandas has `import numpy` in setup.py file, and fails at build time. The pip version in the container is 8.x.x, which isn't aware of these changes (the adoption of these peps is rather recent), and the first version of pip I managed to get it working with is 19.1
