### ISSUE TITLE
where is the copy mechanism implemented?

### ISSUE THREAD

**Issue by gchaperon** [KTH/chai#24]
hi! would some be so kind to point me to the source code where the copy mechanism is implemented?

i am looking at the source code of OpenNMT and the closest I could find was a model called "ContextGate" that apparently performs something similar to whats described in the paper, but they reference a different work for the implementation ([this one](https://arxiv.org/abs/1608.06043), as opposed to [this one](https://arxiv.org/abs/1704.04368) which is referenced in the paper)

thanks in advance!
gabriel

**Comment by chenzimin** [comment]
Hi Gabriel,

You can take a look at this file https://github.com/OpenNMT/OpenNMT-py/blob/fb14f48cb4e185c5169183a65ae26e532e522764/onmt/modules/copy_generator.py.

**Comment by gchaperon** [comment]
thanks a lot!
