### ISSUE TITLE
failed abstraction when buggy line is in a method inside a method

### ISSUE THREAD

**Issue by gchaperon** [KTH/chai#29]
A method can be inside another method by means of an anonymous class. You can see this in this example -> https://github.com/KTH/CodRep-competition/blob/99a116fafcecfabd51853e25b5f43ac2f2dec4d8/Datasets/Dataset4/Tasks/1060.txt#L155

In the case of the example, the algorithm avoids deleting the body of the method containing the buggy line (`touchDragged`), but deletes the body of `MyActor` (the constructor) which also deletes de buggy method.

What could be done to avoid this behaviour? 

Here is the full output of the abstraction process, as you can see, everything gets deleted :-/

```java
/**
 * A simple example of how to use a y-down coordinate system.
 *
 * @author mzechner
 */
public class YDownTest extends GdxTest {
    SpriteBatch batch;

    BitmapFont font;

    TextureRegion region;

    Sprite sprite;

    TextureAtlas atlas;

    Stage stage;

    YDownTest.MyActor image;

    OrthographicCamera camera;

    @Override
    public void create() {
    }

    @Override
    public void resize(int width, int height) {
    }

    @Override
    public void render() {
    }

    /**
     * A very simple actor implementation that does not obey rotation/scale/origin set on the actor. Allows dragging of the actor.
     *
     * @author mzechner
     */
    public class MyActor extends Actor {
        TextureRegion region;

        float lastX;

        float lastY;

        public MyActor(TextureRegion region) {
        }

        @Override
        public void draw(Batch batch, float parentAlpha) {
        }
    }

    @Override
    public void dispose() {
    }
}
```

**Comment by chenzimin** [comment]
Hmmm, this is weird. I remember that this is the issue that I wanted to solve when I wrote `getTopLevelMethod`. Do you know if this happens for all methods inside a method?

**Comment by gchaperon** [comment]
ahh, you are completely right, the algorithm fails here because the method is inside a constructor, not inside a method.
all constructors get nuked so the buggy line is deleted
this also happens for `CtAnonymousExecutable`

for now I will just ignore those (buggy methods inside either constructors or anonymous blocks)

**Comment by gchaperon** [comment]
as discussed in our meeting, i will simply ignore those edge cases.

we found out that method annotations weren't marked correctly. This is a limitation of `spoon` and i will also ignore those cases.
