### ISSUE TITLE
seq2seq4repair-experiments.git not available

### ISSUE THREAD

**Issue by thibolu** [KTH/chai#9]
I'm trying to follow the README to train a model.
I'm getting stuck at the setup section.

`git clone https://github.com/kth-tcs/seq2seq4repair-experiments.git
`
returns the following error:
```
remote: Repository not found.
fatal: repository 'https://github.com/kth-tcs/seq2seq4repair-experiments.git/' not found
```

Thank you for your help

**Comment by chenzimin** [comment]
Hi,
It is because seq2seq4repair-experiments is a private repo and contains code for training on our clusters. I will update the structure and code here in this repo.

**Comment by chenzimin** [comment]
@thibolu You should be able to run the script now.

**Comment by monperrus** [comment]
Thanks a lot @chenzimin 

@thibolu could we close this issue?

**Comment by thibolu** [comment]
Yes, it's good now. Thank you.
